apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: demo-app
    releaseName: demo-dev
    namespace: dev
    valuesFile: values.yaml
