apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod

helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: demo-app
    releaseName: demo-prod
    namespace: prod
    valuesFile: values.yaml
