name: Kubernetes Validation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Validate Kubernetes manifests
        run: |
          find . \( -path "./.github" -prune \) -o \
          \( -name "*.yaml" -o -name "*.yml" \) -print | while read file; do
            echo "Validating $file"
            kubectl apply --dry-run=client --validate=false -f "$file"
          done
