name: Kubernetes Validation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install kubeconform
        run: |
          curl -L https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz \
          | tar xz
          sudo mv kubeconform /usr/local/bin/

      - name: Validate raw Kubernetes manifests
        run: |
          find . \
            \( -path "./.github" -o -path "./charts" \) -prune \
            -o \( -name "*.yaml" -o -name "*.yml" \) -print \
            | while read file; do
                echo "Validating $file"
                kubeconform -ignore-missing-schemas "$file"
              done

      - name: Validate Helm chart
        run: |
          helm template demo-app ./charts/demo-app | kubeconform -summary -ignore-missing-schemas
