name: Kubernetes Validation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Kubeconform
        uses: bmuschko/setup-kubeconform@v1

      - name: Validate Kubernetes manifests
        run: |
          find . \( -path "./.github" -prune \) -o \
          \( -name "*.yaml" -o -name "*.yml" \) -print | xargs kubeconform -summary -ignore-missing-schemas